
import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Hero from "@/components/hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="kr">
        <body className="bg-primary">
        <ThemeProvider attribute="class" defaultTheme="system">
            <Header/>
            <Hero />
            {children}
            <Footer /> 
        </ThemeProvider>
        </body>
    </html>
  );
};