
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "인스타그램",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <div>
            Instagram
        </div>
    );
};