
import UI from "./ui";

export const metadata = {
    title: "넷플릭스",
    description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
        <UI />
    </main>
  );
};